# -*- coding: utf-8 -*-
"""ActualLinearRregression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PoIKmT2kleu9av1sNDLQ4-bN_nm7hcSg
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("rabieelkharoua/students-performance-dataset")

print("Path to dataset files:", path)

import pandas as pd
dataset = pd.read_csv("/content/sample_data/Student_performance_data _.csv")
print(dataset.columns)

x = dataset.drop(columns=['StudentID','GradeClass', 'GPA'])
#x = dataset[['StudyTimeWeekly','Absences']]
#x = dataset[['StudyTimeWeekly','Absences','ParentalSupport','Tutoring','Extracurricular']]
y = dataset[['GPA']]
print(x.head())
print(y.head())

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.1, random_state=42)

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

from sklearn.metrics import mean_squared_error, r2_score
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print("Mean Squared Error:", mse)
print("R-squared:", r2)

import matplotlib.pyplot as plt

plt.scatter(y_test, y_pred, alpha=0.6)
plt.xlabel("Actual GPA Index")
plt.ylabel("Predicted GPA Index")
plt.title("Actual vs Predicted Student GPA")
plt.grid(True)

min_val = min(y_test.min().item(), y_pred.min())
max_val = max(y_test.max().item(), y_pred.max())
plt.plot([min_val, max_val], [min_val, max_val], 'g--', linewidth=2)

plt.show()

"""## Observation

>The model performance is influenced by the relevance of the input features rather than their quantity alone.

---
---

### Case 1: Core Academic Behavior

X =
* StudyTimeWeekly  
* Absences  

Test_split = 0.1

- Mean Squared Error: 0.16  
- R-squared: 0.87  

---
### Case 2: Academic + Support Factors

X =
* StudyTimeWeekly  
* Absences  
* ParentalSupport  
* Tutoring
* Extracurricular

Test_split = 0.1

- Mean Squared Error: 0.05  
- R-squared: 0.94  

---
### Case 3: Full Student Profile

X =
* Age
* Gender
* Ethnicity
* ParentalEducation
* StudyTimeWeekly
* Absences Tutoring
* ParentalSupport
* Extracurricular
* Sports
* Music
* Volunteering

Test_split = 0.1

- Mean Squared Error: 0.038  
- R-squared: 0.95  

---
---
"""