# -*- coding: utf-8 -*-
"""Kmeans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UA8Jg7lvuGF_BtHjDzHZwzV2XfrxiUpF
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("spscientist/students-performance-in-exams")

print("Path to dataset files:", path)

import pandas as pd

dataset = pd.read_csv('/content/sample_data/Student_performance_data _.csv')
X = dataset[['StudyTimeWeekly', 'Absences', 'ParentalSupport', 'Tutoring', 'Extracurricular', 'Sports']]
X.head()

from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=3, random_state=42)
kmeans.fit(X)

X['Cluster'] = kmeans.labels_
X.head()

new_student = pd.DataFrame(
    [[10, 3, 2, 1, 1, 0]],
    columns=X.drop(columns=['Cluster']).columns   # exclude 'Cluster' column
)

print(f"The predicted cluster of the new student is cluster number: {kmeans.predict(new_student)}")

from sklearn.metrics import silhouette_score

inertia = kmeans.inertia_
silhouette_avg = silhouette_score(X, kmeans.labels_)

print(f"Inertia (Sum of Squared Distances): {inertia}")
print(f"Silhouette Score: {silhouette_avg}")

import matplotlib.pyplot as plt

plt.scatter(X.iloc[:, 0], X.iloc[:, 1],
            c=kmeans.labels_, s=50)

plt.scatter(kmeans.cluster_centers_[:, 0],
            kmeans.cluster_centers_[:, 1],
            c='red', marker='X', s=200,
            label='Centroids')

plt.xlabel(X.columns[0])
plt.ylabel(X.columns[1])
plt.title("K-Means Clustering on Student Performance Dataset (k=3)")
plt.legend()
plt.show()

"""**K‑Means clustering was applied to the students performance dataset.**

**k = 3**

***The results of these settings were:***


> Inertia = 93116.237
> Silhouette = 0.37
"""